### ISSUE TITLE
Cancel was called on null

### ISSUE THREAD

**Issue by akashrajkn** [eopeter/flutter_dialpad#3]
Thank you for the plugin. I get the following exception on the latest codebase

```
The following NoSuchMethodError was thrown while finalizing the widget tree:
The method 'cancel' was called on null.
Receiver: null
Tried calling: cancel()

When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      _DialButtonState.dispose (package:flutter_dialpad/flutter_dialpad.dart:220:70)
#2      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4729:12)
#3      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#4      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
```

**Comment by thesipguy** [comment]
I get the same error when closing the widget that is holding the DialPad() widget

**Comment by rehamalraee** [comment]
@thesipguy  @akashrajkn 
Hello! Is it Fixed with you ? if yes how ?

**Comment by akashrajkn** [comment]
@rehamalraee I could not fix it with this package. I ended up making my own dialer :)

**Comment by eopeter** [comment]
This is resolved in the latest version.
